#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: port
    type: string

jobs:
  - job: "arm_windows_${{ parameters.job_name }}"
    pool:
      vmImage: windows-2019
      # vmImage: windows-2022 # (2021-10-04) VS 2022 Preview is not ready for arm64-windows
    timeoutInMinutes: "300"
    steps:
      - task: UsePythonVersion@0
        displayName: "Setup: Python 3.9"
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
      - powershell: env
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port: "${{ parameters.port }}"
          triplet: "arm64-windows"
      - template: steps-publish-logs.yml
        parameters:
          port: "${{ parameters.port }}"
    condition: or(eq(variables['Build.SourceBranchName'], 'main'), startsWith(variables['Build.SourceBranchName'], 'port/${{ parameters.port }}')) # https://stackoverflow.com/a/64657966
