#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: port
    type: string

jobs:
  - job: "linux_${{ parameters.job_name }}"
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: "300"
    steps:
      - powershell: sudo apt-get install -y libnuma-dev
        displayName: "Install APT packages"
      - powershell: pip install typing-extensions pybind11 numpy pyyaml
        displayName: "Install Python packages"
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port: "${{ parameters.port }}"
          triplet: "x64-linux"
      - template: steps-publish-logs.yml
        parameters:
          port: "${{ parameters.port }}"
