#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: port_name
    type: string

jobs:
  - job: "windows_${{ parameters.job_name }}"
    pool:
      vmImage: windows-2019
      # vmImage: windows-2022 # (2021-10-04) VS 2022 Preview is not ready for arm64-windows
    timeoutInMinutes: 300
    steps:
      - task: UsePythonVersion@0
        displayName: "Setup: Python 3.9"
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
      - powershell: env
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}"
          target_triplet: "x64-windows"
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}"
          target_triplet: "x86-windows"
      - template: steps-publish-logs.yml
        parameters:
          port_name: "${{ parameters.port_name }}"
