#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: port
    type: string

jobs:
  - job: "ios_${{ parameters.job_name }}"
    pool:
      vmImage: macOS-11
    timeoutInMinutes: "300"
    steps:
      - powershell: brew install autoconf automake libtool
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port: "${{ parameters.port }}"
          triplet: "x64-ios"
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port: "${{ parameters.port }}"
          triplet: "arm64-ios"
      - template: steps-publish-logs.yml
        parameters:
          port: "${{ parameters.port }}"
