#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: port_name
    type: string

jobs:
  - job: "android_${{ parameters.job_name }}"
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 300
    steps:
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}"
          target_triplet: "arm64-android"
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}"
          target_triplet: "x64-android"
      - template: steps-publish-logs.yml
        parameters:
          port_name: "${{ parameters.port_name }}"
