#
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
# https://github.com/actions/virtual-environments/tree/main/images
# https://github.com/lukka/CppBuildTasks
#

# trigger:
#   - main

pr:
  - main

schedules:
  - cron: "10 4 * * 6"
    displayName: "Weekly check"
    branches:
      include:
        - main

variables:
  - name: VCPKG_DISABLE_METRICS
    value: "true"

jobs:
  - job: "windows_2019"
    pool:
      vmImage: windows-2019
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
        displayName: "Setup Python 3.9"
      - powershell: pip install typing-extensions pybind11 numpy
      - powershell: env
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3"
          target_triplet: "x64-windows"
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3-test"
          target_triplet: "x86-windows"

  - job: "ubuntu_2004"
    pool:
      vmImage: ubuntu-20.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
        displayName: "Setup Python 3.9"
      - powershell: pip install typing-extensions pybind11 numpy
      - powershell: env
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3"
          target_triplet: "x64-linux"
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3-test"
          target_triplet: "x64-linux"

  - job: "macos_15"
    pool:
      vmImage: macOS-10.15
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
        displayName: "Setup Python 3.9"
      - powershell: pip install typing-extensions pybind11 numpy
      - powershell: env
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3"
          target_triplet: "x64-osx"
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3-test"
          target_triplet: "arm64-osx"
