#
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
# https://github.com/actions/virtual-environments/tree/main/images
# https://github.com/lukka/CppBuildTasks
#

# trigger:
#   - main

pr:
  - main

schedules:
  - cron: "10 4 * * 6"
    displayName: "Weekly check"
    branches:
      include:
        - main

variables:
  - name: VCPKG_DISABLE_METRICS
    value: "true"

jobs:
  - job: "windows_2019"
    pool:
      vmImage: windows-2019
    steps:
      - task: UsePythonVersion@0
        displayName: "Setup: Python 3.9"
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
      - powershell: pip install typing-extensions pybind11
        displayName: "Install Python packages"
      - powershell: env
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3-test"
          target_triplet: "x64-windows"
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3-test"
          target_triplet: "x86-windows"
      - powershell: pip list
        displayName: "Show installed Python packages"

  - job: "ubuntu_2004"
    pool:
      vmImage: ubuntu-20.04
    steps:
      - powershell: |
          python3 -m pip install typing-extensions numpy
          pip show numpy
        displayName: "Install Python packages"
      - powershell: |
          $site_package_dir=$(python3 -m site --user-site)
          Write-Output $site_package_dir
          if (Test-Path $site_package_dir) {
            Get-ChildItem $site_package_dir
          }
        displayName: "Check Python User Site"
      - powershell: env
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3-test"
          target_triplet: "x64-linux"
      - powershell: pip list
        displayName: "Show installed Python packages"

  - job: "macos_15"
    pool:
      vmImage: macOS-10.15
    steps:
      - task: UsePythonVersion@0
        displayName: "Setup: Python 3.9"
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
      - powershell: pip install pybind11
        displayName: "Install Python packages"
      - powershell: env
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3-test"
          target_triplet: "x64-osx"
      - template: azure/run-vcpkg-with-overlay.yml
        parameters:
          port_name: "vcpkg-host-python3-test"
          target_triplet: "arm64-osx"
      - powershell: pip list
        displayName: "Show installed Python packages"
