#
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
# https://github.com/actions/virtual-environments/tree/main/images
# https://github.com/lukka/CppBuildTasks
#

# trigger:
#   - main

pr:
  - main

schedules:
  - cron: "10 4 * * 6"
    displayName: "Weekly check"
    branches:
      include:
        - main

variables:
  - name: VCPKG_DISABLE_METRICS
    value: "true"

stages:
  - stage: "Scripts"
    jobs:
      - job: "windows_2019"
        pool:
          vmImage: windows-2019
        steps:
          - powershell: env
          - task: PowerShell@2
            inputs:
              filePath: 'scripts/check-sha.ps1'
          - powershell: |
              Get-ChildItem $(CONDA)
              Push-Location "$(CONDA)\\condabin"
                ./conda install pyqt
              Pop-Location
              Get-ChildItem "$(CONDA)\\Library"
              Get-ChildItem "$(CONDA)\\Library\\pkgconfig"
              Get-ChildItem "$(CONDA)\\Library\\cmake"
              Get-ChildItem "$(CONDA)\\Library\\lib\\cmake"

          # - task: CMake@1
          #   inputs:
          #     cmakeArgs: "-S ../tests"
          #     runInsideShell: true

  # - stage: "Ports" # Check build status of the ports
  #   jobs:
  #     - template: azure/jobs-normal-port.yml
  #       parameters:
  #         job_name: "zlib_ng"
  #         port_name: "zlib-ng"
  #     - template: azure/jobs-python3-port.yml
  #       parameters:
  #         job_name: "vcpkg_host_python3"
  #         port_name: "vcpkg-host-python3"
  #     - template: azure/jobs-normal-port.yml
  #       parameters:
  #         job_name: "openssl3"
  #         port_name: "openssl3"
  #     - template: azure/jobs-uwp-port.yml
  #       parameters:
  #         job_name: "openssl3"
  #         port_name: "openssl3"

  # - stage: "Registry" # todo: Use of this registry
  #   jobs:
  #     - job: "windows_2022"
  #       pool:
  #         vmImage: windows-2022
  #       steps:
  #         - powershell: Write-Output "Not implemented"

  # todo: Deploy stage
  #   Status notification + GitHub release
